### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by mdsmendes94** [AnimeshRy/yt2spot#2]
```
PS C:\Users\Matheus\Documents\yt2spot-main> python main.py
Traceback (most recent call last):
  File "C:\Users\Matheus\Documents\yt2spot-main\main.py", line 37, in <module>
    main()
  File "C:\Users\Matheus\Documents\yt2spot-main\main.py", line 13, in main
    yt = Youtube()
  File "C:\Users\Matheus\Documents\yt2spot-main\youtube.py", line 43, in __init__
    self.api = build(Youtube.API_SERVICE_NAME,
  File "C:\Users\Matheus\AppData\Local\Programs\Python\Python310\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Matheus\AppData\Local\Programs\Python\Python310\lib\site-packages\googleapiclient\discovery.py", line 295, in build
    raise e
  File "C:\Users\Matheus\AppData\Local\Programs\Python\Python310\lib\site-packages\googleapiclient\discovery.py", line 270, in build
    content = _retrieve_discovery_doc(
  File "C:\Users\Matheus\AppData\Local\Programs\Python\Python310\lib\site-packages\googleapiclient\discovery.py", line 376, in _retrieve_discovery_doc
    resp, content = req.execute(num_retries=num_retries)
  File "C:\Users\Matheus\AppData\Local\Programs\Python\Python310\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Matheus\AppData\Local\Programs\Python\Python310\lib\site-packages\googleapiclient\http.py", line 915, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/discovery/v1/apis/youtube/v3/rest?key=%3C%3E returned "API key not valid. Please pass a valid API key.". Details: "[{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'API_KEY_INVALID', 'domain': 'googleapis.com', 'metadata': {'service': 'youtube.googleapis.com'}}]">
PS C:\Users\Matheus\Documents\yt2spot-main>
```

**Comment by AnimeshRy** [comment]
Please follow the instructions to get a API key for you google account. I haven't tested the script recently but the problem looks lik e a configuration issue
